import { revalidatePath } from 'next/cache';
import { requireAuth } from '../../lib/auth';
import { db, loadSalesPipeline, calculateInventoryForecast } from '../../lib/db';
import Shell from '../_shell';
function num(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function date(v){return v?new Date(v).toLocaleDateString():'—'}
async function saveSettings(formData){'use server';requireAuth();const s=db();const payload={market_id:String(formData.get('market_id')),reorder_lead_days:Number(formData.get('reorder_lead_days')),safety_stock_days:Number(formData.get('safety_stock_days')),next_cargo_size_nt:Number(formData.get('next_cargo_size_nt')),updated_at:new Date().toISOString()};const {error}=await s.from('market_settings').upsert(payload,{onConflict:'market_id'});if(error)throw error;revalidatePath('/inventory');revalidatePath('/dashboard')}
export default async function Inventory(){requireAuth();const data=await loadSalesPipeline();const f=calculateInventoryForecast(data);const settings=data.marketSettings||{};return <Shell><div className="top"><div><h1 className="title">Toledo Inventory & Reorder Forecast</h1><div className="muted">Probability-weighted customer throughput drives projected terminal inventory.</div></div></div>
<div className="grid"><div className="card"><div className="metric-label">Saleable cargo</div><div className="metric">{num(f.qty)} NT</div></div><div className="card"><div className="metric-label">Weighted weekly demand</div><div className="metric">{num(f.activeWeeklyDemand)} NT</div></div><div className="card"><div className="metric-label">Weeks of supply</div><div className="metric">{f.weeksOfSupply?f.weeksOfSupply.toFixed(1):'—'}</div></div><div className="card"><div className="metric-label">Projected stockout</div><div className="metric small">{date(f.stockoutDate)}</div></div><div className="card"><div className="metric-label">Target Cargo #2 arrival</div><div className="metric small">{date(f.targetArrivalDate)}</div></div><div className="card"><div className="metric-label">Reorder deadline</div><div className="metric small">{date(f.reorderDeadline)}</div></div></div>
<form action={saveSettings} className="form section"><input type="hidden" name="market_id" value={data.market.id}/><h2>Reorder assumptions</h2><div className="form-grid"><div className="field"><label>Total procurement / sailing lead time (days)</label><input name="reorder_lead_days" type="number" defaultValue={settings.reorder_lead_days||35}/></div><div className="field"><label>Safety stock (days)</label><input name="safety_stock_days" type="number" defaultValue={settings.safety_stock_days||7}/></div><div className="field"><label>Next cargo size (NT)</label><input name="next_cargo_size_nt" type="number" step="1" defaultValue={settings.next_cargo_size_nt||20519.24}/></div></div><div style={{marginTop:16}}><button className="btn">Save reorder assumptions</button></div></form>
<div className="two section"><div className="card"><h2>Decision signals</h2><p><b>Probability-weighted target pipeline:</b> {num(f.totalWeightedTarget)} NT</p><p><b>Safety stock:</b> {num(f.safetyStockNT)} NT</p><p><b>Lead time:</b> {f.leadDays} days</p><p><b>Next cargo size:</b> {num(f.nextCargoSizeNT)} NT</p>{f.reorderDeadline?<div className="notice">To maintain {f.safetyDays} days of safety stock, have Cargo #2 scheduled to arrive by <b>{date(f.targetArrivalDate)}</b>. Planning/order deadline: <b>{date(f.reorderDeadline)}</b>.</div>:<div className="notice">No stockout is projected under the current probability-weighted pipeline.</div>}</div><div className="card"><h2>Pipeline coverage</h2><p><b>Total target customer tons:</b> {num(f.totalTarget)} NT</p><p><b>Probability-weighted target:</b> {num(f.totalWeightedTarget)} NT</p><p><b>Current cargo:</b> {num(f.qty)} NT</p><p><b>Target gap vs cargo:</b> {num(Math.max(0,f.qty-f.totalWeightedTarget))} NT</p></div></div>
<div className="section"><h2>Weekly inventory forecast</h2><div className="table-wrap"><table className="table"><thead><tr><th>Week</th><th>Week start</th><th>Weighted planned demand</th><th>Shipped</th><th>Ending inventory</th><th>Customer detail</th></tr></thead><tbody>{f.weeks.slice(0,52).map(w=><tr key={w.week}><td>{w.week}</td><td>{date(w.weekStart)}</td><td>{num(w.planned_nt)}</td><td>{num(w.shipped_nt)}</td><td>{num(w.ending_inventory_nt)}</td><td>{w.details.map(d=>`${d.customer}: ${num(d.weighted_nt)} NT`).join(' · ')||'—'}</td></tr>)}</tbody></table></div></div></Shell>}
