import { requireAuth } from '../../lib/auth';
import { loadSalesPipeline, calculateModel, calculateInventoryForecast } from '../../lib/db';
import Shell from '../_shell';
function money(v){return `$${Number(v||0).toFixed(2)}`} function num(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})} function date(v){return v?new Date(v).toLocaleDateString():'—'}
export default async function Dashboard(){requireAuth();const data=await loadSalesPipeline();const m=calculateModel(data);const f=calculateInventoryForecast(data);const pipelineCount=data.customerPlans?.length||0;return <Shell><div className="top"><div><h1 className="title">Toledo Executive Dashboard</h1><div className="muted">Cargo economics + customer pipeline + inventory decision signals</div></div></div>
<div className="grid"><div className="card"><div className="metric-label">Modeled Cost / NT</div><div className="metric">{money(m.modeledCost)}</div></div><div className="card"><div className="metric-label">Reference Sell Price</div><div className="metric">{money(m.sellPrice)}</div></div><div className="card"><div className="metric-label">Reference Margin / NT</div><div className="metric">{money(m.marginNT)}</div></div><div className="card"><div className="metric-label">Weighted pipeline</div><div className="metric">{num(f.totalWeightedTarget)} NT</div></div><div className="card"><div className="metric-label">Projected stockout</div><div className="metric small">{date(f.stockoutDate)}</div></div><div className="card"><div className="metric-label">Reorder deadline</div><div className="metric small">{date(f.reorderDeadline)}</div></div></div>
<div className="two section"><div className="card"><h2>Sales & inventory</h2><p><b>Customer plans:</b> {pipelineCount}</p><p><b>Saleable cargo:</b> {num(f.qty)} NT</p><p><b>Weighted weekly demand:</b> {num(f.activeWeeklyDemand)} NT</p><p><b>Weeks of supply:</b> {f.weeksOfSupply?f.weeksOfSupply.toFixed(1):'—'}</p><p><b>Target Cargo #2 arrival:</b> {date(f.targetArrivalDate)}</p>{f.reorderDeadline&&<div className="notice">Reorder / nominate by <b>{date(f.reorderDeadline)}</b> under current pipeline assumptions.</div>}</div>
<div className="card"><h2>Cost & financing</h2><table className="table"><tbody><tr><td>Base cargo + Toledo terminal</td><td>{money(m.base)}/NT</td></tr><tr><td>Dynamic warehouse storage</td><td>{money(m.storageNT)}/NT</td></tr><tr><td>Available A/R financing</td><td>{money(m.arFinanceNT)}/NT</td></tr><tr><th>Modeled total</th><th>{money(m.modeledCost)}/NT</th></tr></tbody></table><p><b>SOFR:</b> {m.sofr.toFixed(2)}% ({m.sofrDate||'—'})</p><p><b>Bank rate:</b> {(m.sofr+m.spread).toFixed(2)}%</p></div></div>
<div className="section card"><h2>Pipeline coverage</h2><div className="bar"><div style={{width:`${Math.min(100,f.qty?f.totalWeightedTarget/f.qty*100:0)}%`}}/></div><p>{num(f.totalWeightedTarget)} probability-weighted target tons against {num(f.qty)} NT of current cargo.</p></div></Shell>}
